DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS team;

CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  phone TEXT,
  collab_id INTEGER,
  FOREIGN KEY (collab_id) REFERENCES team (id)
);

CREATE TABLE team (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  creator_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL,
  FOREIGN KEY (creator_id) REFERENCES user (id)
);