users = [
    {
        "first_name": "Brendon",
        "last_name": "Crave",
        "email": "brendoncrave@devpipeline.com",
        "password": "123",
        "username": "bcrave",
        "collabs": [1, 3, 4, 16],
        "phone": "123-456-789",
    },
    {
        "first_name": "Ludovico",
        "last_name": "Elen",
        "email": "lelen0@blogs.com",
        "password": "dvmHCVAg",
        "username": "lelen0",
        "collabs": [2, 4, 1, 15],
        "phone": "762-183-0436",
    },
    {
        "first_name": "Carmelia",
        "last_name": "O'Lochan",
        "email": "colochan1@hhs.gov",
        "password": "JrSgJeMG3Fy",
        "username": "colochan1",
        "collabs": [3, 1, 2, 14],
        "phone": "769-212-1071",
    },
    {
        "first_name": "Miof mela",
        "last_name": "Craigs",
        "email": "mcraigs2@army.mil",
        "password": "KTr6rQiy",
        "username": "mcraigs2",
        "collabs": [4, 2, 1, 13],
        "phone": "142-515-2992",
    },
    {
        "first_name": "Lothario",
        "last_name": "Saldler",
        "email": "lsaldler3@ovh.net",
        "password": "3gQ5QsQgt1t",
        "username": "lsaldler3",
        "collabs": [5, 2, 3, 12],
        "phone": "604-721-1905",
    },
    {
        "first_name": "Rolph",
        "last_name": "Abrehart",
        "email": "rabrehart4@live.com",
        "password": "By5t3Tb7",
        "username": "rabrehart4",
        "collabs": [6, 3, 4, 10],
        "phone": "299-746-6463",
    },
    {
        "first_name": "Corbet",
        "last_name": "Klewi",
        "email": "cklewi5@instagram.com",
        "password": "mLc1uA",
        "username": "cklewi5",
        "collabs": [7, 3, 5, 11],
        "phone": "916-592-6492",
    },
    {
        "first_name": "Shaine",
        "last_name": "Kernar",
        "email": "skernar6@example.com",
        "password": "KCkdrSy8u",
        "username": "skernar6",
        "collabs": [8, 4, 6, 9],
        "phone": "144-737-4623",
    },
    {
        "first_name": "Jodie",
        "last_name": "Plaid",
        "email": "jplaid7@ox.ac.uk",
        "password": "u5VRdUg",
        "username": "jplaid7",
        "collabs": [9, 4, 7, 8],
        "phone": "181-339-3202",
    },
    {
        "first_name": "Cheston",
        "last_name": "Le Floch",
        "email": "clefloch8@smh.com.au",
        "password": "m9uYY8",
        "username": "clefloch8",
        "collabs": [10, 5, 9, 7],
        "phone": "938-720-4412",
    },
    {
        "first_name": "Mersey",
        "last_name": "Eyre",
        "email": "meyre9@nyu.edu",
        "password": "gjQvPOY",
        "username": "meyre9",
        "collabs": [11, 5, 10, 6],
        "phone": "331-236-1766",
    },
    {
        "first_name": "Abramo",
        "last_name": "Maharg",
        "email": "amaharga@wired.com",
        "password": "mXg56MAwZ",
        "username": "amaharga",
        "collabs": [12, 6, 11, 5],
        "phone": "453-511-1301",
    },
    {
        "first_name": "Rosemary",
        "last_name": "Glandon",
        "email": "rglandonb@bbc.co.uk",
        "password": "PKjZ2Vt6eS",
        "username": "rglandonb",
        "collabs": [13, 6, 12, 4],
        "phone": "807-590-5675",
    },
    {
        "first_name": "Denice",
        "last_name": "Hirth",
        "email": "dhirthc@spotify.com",
        "password": "Pt2TulN7Et",
        "username": "dhirthc",
        "collabs": [14, 7, 13, 3],
        "phone": "215-935-1340",
    },
    {
        "first_name": "Sebastian",
        "last_name": "Vasilkov",
        "email": "svasilkovd@technorati.com",
        "password": "IGrD5filOPI",
        "username": "svasilkovd",
        "collabs": [15, 7, 14, 2],
        "phone": "573-708-5629",
    },
    {
        "first_name": "Brandon",
        "last_name": "Graves",
        "email": "brandongraves@gmail.com",
        "password": "1312",
        "username": "D4rkBrandon",
        "collabs": [16, 8, 15, 1],
        "phone": "467-885-4490",
    },
]
teams = [
    {"name": "Keeling, Ruecker and Kulas", "owner_id": 1},
    {"name": "Schumm, Metz and Dooley", "owner_id": 2},
    {"name": "Mraz and Sons", "owner_id": 3},
    {"name": "Pfannerstill, Wyman and Denesik", "owner_id": 4},
    {"name": "Turner Group", "owner_id": 5},
    {"name": "Feeney-Kozey", "owner_id": 6},
    {"name": "Nikolaus and Sons", "owner_id": 7},
    {"name": "Hackett-Lakin", "owner_id": 8},
    {"name": "Jacobson Inc", "owner_id": 9},
    {"name": "Kiehn Inc", "owner_id": 10},
    {"name": "Bergstrom, Cremin and Kozey", "owner_id": 11},
    {"name": "Price Inc", "owner_id": 12},
    {"name": "Lockman-Kohler", "owner_id": 13},
    {"name": "Bode-Stoltenberg", "owner_id": 14},
    {"name": "Runolfsson and Sons", "owner_id": 15},
    {"name": "Johnston LLC", "owner_id": 16},
]
