users = [
    {
        "id": 1,
        "first_name": "Danie",
        "last_name": "Floodgate",
        "email": "dfloodgate0@themeforest.net",
        "password": "NBCzUDjV",
        "username": "dfloodgate0",
        "phone": "519-315-7106",
    },
    {
        "id": 2,
        "first_name": "Vale",
        "last_name": "Ateggart",
        "email": "vateggart1@oakley.com",
        "password": "CJ4hbjQ",
        "username": "vateggart1",
        "phone": "633-832-8410",
    },
    {
        "id": 3,
        "first_name": "Abigale",
        "last_name": "MacKnocker",
        "email": "amacknocker2@altervista.org",
        "password": "Pu3aB6u",
        "username": "amacknocker2",
        "phone": "528-643-2041",
    },
    {
        "id": 4,
        "first_name": "Margarete",
        "last_name": "Aseef",
        "email": "maseef3@instagram.com",
        "password": "XnjOJAXK2e",
        "username": "maseef3",
        "phone": "693-597-5013",
    },
    {
        "id": 5,
        "first_name": "Dotti",
        "last_name": "Noye",
        "email": "dnoye4@cocolog-nifty.com",
        "password": "JpxN2c59g",
        "username": "dnoye4",
        "phone": "732-640-1916",
    },
    {
        "id": 6,
        "first_name": "Jacqueline",
        "last_name": "MacAulay",
        "email": "jmacaulay5@barnesandnoble.com",
        "password": "IkdeEvdx",
        "username": "jmacaulay5",
        "phone": "352-929-9164",
    },
    {
        "id": 7,
        "first_name": "Silvia",
        "last_name": "Loveland",
        "email": "sloveland6@indiatimes.com",
        "password": "DwXd0i17nrF",
        "username": "sloveland6",
        "phone": "886-134-6617",
    },
    {
        "id": 8,
        "first_name": "Willem",
        "last_name": "Westman",
        "email": "wwestman7@acquirethisname.com",
        "password": "O874aC9Wj",
        "username": "wwestman7",
        "phone": "846-770-0360",
    },
    {
        "id": 9,
        "first_name": "Matthias",
        "last_name": "Loble",
        "email": "mloble8@ibm.com",
        "password": "FLD80mFAG",
        "username": "mloble8",
        "phone": "989-942-4521",
    },
    {
        "id": 10,
        "first_name": "Nonie",
        "last_name": "Krimmer",
        "email": "nkrimmer9@wikia.com",
        "password": "GaaxYe3BT",
        "username": "nkrimmer9",
        "phone": "114-751-4954",
    },
    {
        "id": 11,
        "first_name": "Falito",
        "last_name": "Torrijos",
        "email": "ftorrijosa@deviantart.com",
        "password": "NrHL7j2acLh",
        "username": "ftorrijosa",
        "phone": "690-759-2439",
    },
    {
        "id": 12,
        "first_name": "Karlyn",
        "last_name": "Hardistry",
        "email": "khardistryb@cdbaby.com",
        "password": "zCwM4dd",
        "username": "khardistryb",
        "phone": "207-910-8269",
    },
    {
        "id": 13,
        "first_name": "Deina",
        "last_name": "Ackerman",
        "email": "dackermanc@angelfire.com",
        "password": "pIG9krW",
        "username": "dackermanc",
        "phone": "268-756-5175",
    },
    {
        "id": 14,
        "first_name": "Zechariah",
        "last_name": "Dawltrey",
        "email": "zdawltreyd@wix.com",
        "password": "VtzMYjsuIejL",
        "username": "zdawltreyd",
        "phone": "423-484-2422",
    },
    {
        "id": 15,
        "first_name": "Efrem",
        "last_name": "Rubinovitsch",
        "email": "erubinovitsche@is.gd",
        "password": "V9NEqN",
        "username": "erubinovitsche",
        "phone": "706-480-4742",
    },
]
