users = [
    {
        "first_name": "Brendon",
        "last_name": "Crave",
        "email": "brendoncrave@devpipeline.com",
        "password": "123",
        "username": "bcrave",
        "phone": "123-456-789",
    },
    {
        "first_name": "Ludovico",
        "last_name": "Elen",
        "email": "lelen0@blogs.com",
        "password": "dvmHCVAg",
        "username": "lelen0",
        "phone": "762-183-0436",
    },
    {
        "first_name": "Carmelia",
        "last_name": "O'Lochan",
        "email": "colochan1@hhs.gov",
        "password": "JrSgJeMG3Fy",
        "username": "colochan1",
        "phone": "769-212-1071",
    },
    {
        "first_name": "Miof mela",
        "last_name": "Craigs",
        "email": "mcraigs2@army.mil",
        "password": "KTr6rQiy",
        "username": "mcraigs2",
        "phone": "142-515-2992",
    },
    {
        "first_name": "Lothario",
        "last_name": "Saldler",
        "email": "lsaldler3@ovh.net",
        "password": "3gQ5QsQgt1t",
        "username": "lsaldler3",
        "phone": "604-721-1905",
    },
    {
        "first_name": "Rolph",
        "last_name": "Abrehart",
        "email": "rabrehart4@live.com",
        "password": "By5t3Tb7",
        "username": "rabrehart4",
        "phone": "299-746-6463",
    },
    {
        "first_name": "Corbet",
        "last_name": "Klewi",
        "email": "cklewi5@instagram.com",
        "password": "mLc1uA",
        "username": "cklewi5",
        "phone": "916-592-6492",
    },
    {
        "first_name": "Shaine",
        "last_name": "Kernar",
        "email": "skernar6@example.com",
        "password": "KCkdrSy8u",
        "username": "skernar6",
        "phone": "144-737-4623",
    },
    {
        "first_name": "Jodie",
        "last_name": "Plaid",
        "email": "jplaid7@ox.ac.uk",
        "password": "u5VRdUg",
        "username": "jplaid7",
        "phone": "181-339-3202",
    },
    {
        "first_name": "Cheston",
        "last_name": "Le Floch",
        "email": "clefloch8@smh.com.au",
        "password": "m9uYY8",
        "username": "clefloch8",
        "phone": "938-720-4412",
    },
    {
        "first_name": "Mersey",
        "last_name": "Eyre",
        "email": "meyre9@nyu.edu",
        "password": "gjQvPOY",
        "username": "meyre9",
        "phone": "331-236-1766",
    },
    {
        "first_name": "Abramo",
        "last_name": "Maharg",
        "email": "amaharga@wired.com",
        "password": "mXg56MAwZ",
        "username": "amaharga",
        "phone": "453-511-1301",
    },
    {
        "first_name": "Rosemary",
        "last_name": "Glandon",
        "email": "rglandonb@bbc.co.uk",
        "password": "PKjZ2Vt6eS",
        "username": "rglandonb",
        "phone": "807-590-5675",
    },
    {
        "first_name": "Denice",
        "last_name": "Hirth",
        "email": "dhirthc@spotify.com",
        "password": "Pt2TulN7Et",
        "username": "dhirthc",
        "phone": "215-935-1340",
    },
    {
        "first_name": "Sebastian",
        "last_name": "Vasilkov",
        "email": "svasilkovd@technorati.com",
        "password": "IGrD5filOPI",
        "username": "svasilkovd",
        "phone": "573-708-5629",
    },
    {
        "first_name": "Basia",
        "last_name": "Abbison",
        "email": "babbisone@soundcloud.com",
        "password": "rMOPjiHE6",
        "username": "babbisone",
        "phone": "467-885-4490",
    },
]
